name: PEP8 Compliance, Spellcheck, & Docstring

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install -r requirements_testing.txt
    - name: Run flake8
      run: flake8 pylossless docs --exclude pylossless/__init__.py
    - name: Run Codespell
      run: codespell pylossless docs --skip docs/source/generated
    - name: Check Numpy Format Docstring
      run: pydocstyle pylossless

