name: PEP8 Compliance, Spellcheck, & Docstring

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: pip install -r requirements_testing.txt
    - name: Run flake8
      run: flake8 pylossless docs tests --exclude pylossless/__init__.py
    - name: Run Codespell
      run: codespell pylossless docs tests --skip docs/source/generated
    - name: Check Numpy Format Docstring
      run: pydocstyle pylossless tests

