name: Test pipeline (Simulated EEG)

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Pylossless & Deps
      run: pip install -e .
    - name: Install testing dependencies
      run: pip install -r requirements_testing.txt
    - name: Test simulated EEG
      run: pytest tests/test_simulated.py
    - name: Test sample file
      run: pytest tests/test_simulated.py
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v3
      with:
          token: ${{secrets.CODECOV_TOKEN}}
